### PR TITLE
Use map factory in getValues

### LINKED ISSUE #1096: Bug: SmallRyeConfig#getValues: mapFactory is not used
`io.smallrye.config.SmallRyeConfig#getValues(java.lang.String, org.eclipse.microprofile.config.spi.Converter<K>, org.eclipse.microprofile.config.spi.Converter<V>, java.util.function.IntFunction<java.util.Map<K,V>>)`

```java
public <K, V> Map<K, V> getValues(
    String name,
    Converter<K> keyConverter,
    Converter<V> valueConverter,
    IntFunction<Map<K, V>> mapFactory // 1️⃣ any Map could be created
){
  try {
    // 2️⃣ but in most cases caller will receive HashMap (with optional ClassCastException)
    return getValue(name, newMapConverter(keyConverter, valueConverter));
  } catch (NoSuchElementException e) {
    Map<String, String> mapKeys = getMapKeys(name);
    if (mapKeys.isEmpty()) {
        throw new NoSuchElementException(ConfigMessages.msg.propertyNotFound(name));
    }
    // 3️⃣ only this branch creates required type of Map
    Map<K, V> map = mapFactory.apply(mapKeys.size());
    for (Map.Entry<String, String> entry : mapKeys.entrySet()){
       map.put(convertValue(ConfigValue.builder().withName(entry.getKey()).withValue(entry.getKey()).build(),
                keyConverter), getValue(entry.getValue(), valueConverter));
    }
```

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #1096

### CODE REVIEW

File: implementation/src/main/java/io/smallrye/config/Converters.java [hunk 1]
```diff
@@ -322,9 +322,15 @@ public static <A, T> Converter<A> newArrayConverter(Converter<? extends T> itemC
      * @param <V> the type of the values
      * @return the new converter (not {@code null})
      */
+    @Deprecated
```
Comment (dmlloyd) [inline implementation/src/main/java/io/smallrye/config/Converters.java:325]: Why deprecate this one?

Comment (radcortez) [reply implementation/src/main/java/io/smallrye/config/Converters.java:325]: For the collection converter, we don't offer an API method without the factory, so I wanted to make the API consistent. I guess we could also add a method API that defaults the collection type like the map converter.
