### PR TITLE
Moved ConfigProperties injection tests to a separate class.

### LINKED ISSUE #475: ConfigProperties no prefix bug
Injecting a `ConfigProperties` class, [without a prefix defined](https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_inject_the_bean_annotated_with_code_configproperties_code), leads to `io.smallrye.config.inject.ConfigExtension.validate` checking for the desired Config Property without the intended prefix included. If this incorrect Config Property check isn't found a `java.util.NoSuchElementException` is thrown.

For example, Injecting:
```
@Inject
@ConfigProperties
ConfigPropertiesPOJO details;
```

Where ConfigPropertiesPOJO:
```
@ConfigProperties(prefix = "myPrefix")
@Dependent
public class ConfigPropertiesPOJO {
    public String validkey;
}
```

With the following in a Config Source:
```
myPrefix.validkey=validValue
```

Leads to checks for `myPrefix.validkey` (intentionally) AND `validkey` (unintentionally) which throws `java.util.NoSuchElementException: SRCFG00014: Property validkey not found`.

This isn't thrown in the TCKs since in all the examples both `<prefix>.<key>` and `<key>` are unintentionally defined in the Config Sources. E.g. in `customer.name ` and `name ` in [ConfigPropertiesTest.java](https://github.com/eclipse/microprofile-config/blob/93943308fefcca5d5b484ff3b1f8e080589f64ab/tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigPropertiesTest.java#L100).

This issue did not occur in a previous iteration of smallrye-config:2.0.0 (though I can't remember which one... perhaps as far back as RC1?)

### PR DESCRIPTION
**Pull request by radcortez**
Fixes #475

### CODE REVIEW

**Review by Emily-Jiang — DISMISSED** [review]

File: cdi/src/test/java/io/smallrye/config/inject/ConfigPropertiesInjectionTest.java [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+@ExtendWith(WeldJunit5Extension.class)
+public class ConfigPropertiesInjectionTest extends InjectionTest {
+    @WeldSetup
+    WeldInitiator weld = WeldInitiator
+            .from(ConfigExtension.class, ConfigPropertiesInjectionTest.class, Server.class)
+            .inject(this)
+            .build();
+
+    @Inject
+    Server server;
```
Comment (Emily-Jiang) [inline cdi/src/test/java/io/smallrye/config/inject/ConfigPropertiesInjectionTest.java:33]: This injection should not work.
